name: Push builds

on:
  push:
    branches:
      - main
      - fix-html5

jobs:
  build-web:
    permissions:
      contents: write

    uses: ./.github/workflows/build.yml
    with:
      platform: Web
      name: roll
      output_name: index.html

  build-windows:
    uses: ./.github/workflows/build.yml
    with:
      platform: Windows
      name: roll
      output_name: ROLL.exe

  build-mac:
    uses: ./.github/workflows/build.yml
    with:
      platform: macOS
      name: roll
      output_name: ROLL.macos.zip

  build-linux:
    uses: ./.github/workflows/build.yml
    with:
      platform: Linux
      name: roll
      output_name: ROLL.linux.x86_64